### PR TITLE
Create from.js

### PR DESCRIPTION
**Pull request by tracker1**
Add Array.from polyfill

### CODE REVIEW

**Comment by ff6347** [comment]
Cool. Thanks for the PR. So what can we convert with this polyfill?

```js
#include "../Array/from.js"
$.writeln(Array.from("foo"));
// => f,o,o
$.writeln(Array.from(app.activeDocument.pages));
// => [object Page]
```
- Works with strings ☑️
- does not work with InDesign collection objects. ❌
Is there a way to make this happen? I would expect that it works like converting NodeLists in the Browser.

**Comment by tracker1** [comment]
Will look into making it work with strings and indesign collections.

**Comment by ff6347** [comment]
IT Works with strings. Would be great if it worked with any kind of collection. Not only InDesign

**Comment by tracker1** [comment]
It should work with anything that has a `.length` property that's numeric and finite, looking at the code.

**Comment by ff6347** [comment]
Yes it does. Stupid me. In a new ID document there is only one page! m(

**Comment by ff6347** [comment]
And its on the registry https://www.npmjs.com/package/extendscript-es6-shim

**Comment by ff6347** [comment]
Thanks

**Pull request merged**
