### PR TITLE
Array reduce polyfill

### PR DESCRIPTION
**Pull request by yahiaboudah**
Just added another polyfill.

### CODE REVIEW

**Comment by ff6347** [comment]
Hi @yahiaboudah Sorry the notification slipped through. Thanks for the contribution. 2 Questions.

1. Where does the polyfill come from? Can you add a source as comment
2. Please also run the bundle process after contribution (should be automated bit is not yet done so)

**Comment by ff6347** [comment]
@yahiaboudah why close this?

**Comment by yahiaboudah** [comment]
I just opened a new pull request.

**Comment by yahiaboudah** [comment]
https://github.com/ExtendScript/extendscript-es6-shim/pull/8

**Pull request closed without merging**
